name: Visor Code Review

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: probelabs/visor@v0.1.9
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          
